name: ✅ test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: npm run lint --workspace packages/x
      - run: npm run tsc --noEmit --workspace packages/x
      - run: npm run compile --workspace packages/x
      - run: npm run test --workspace packages/x -- --coverage
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
